---
title: Society of Women Engineers
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: posts
    type: posts
  values:
    layout: default
    permalink: "/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
  values:
    layout: default
url: http://www.sampledomainpleasechange.com
baseurl: 
permalink: pretty
exclude:
- ".git"
- ".gitignore"
- ".DS_Store"
- ".sass-cache"
- package.json
- Gruntfile.js
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- LICENSE
sponsor_logos:
- "/uploads/we_local_logo.png"
- "/uploads/we_local_logo.png"
- "/uploads/we_local_logo.png"
events:
- event_name: Sample Event Title
  event_date: 2017-06-20 18:11:00.000000000 Z
  event_url: http://swe.ucsd.edu
- event_name: Sample Event Title
  event_date: 2017-06-14 00:00:00.000000000 Z
  event_url: http://swe.ucsd.edu
